# DO NOT EDIT THIS FILE!
#
# Python module lista01__POA generated by omniidl

import omniORB
omniORB.updateModule("lista01__POA")

# ** 1. Stub files contributing to this module
import ex1_idl

# ** 2. Sub-modules

# ** 3. End
